spring:
  application:
    name: api-gateway
#zuul:
  #routes:
    #test:
      #path: /test_service/**
     # serviceId: eureka-client-1
     #url:http
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZon: http://localhost:8761/eureka/

